# url: https://jlstewart12.github.io
# baseurl: /JS_Portfolio_E/

# Site settings
title: Jeremy Stewart
email: jlstewart12@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
author: Jeremy Stewart
locale: "en-US"

# Team names, titles and social links
people:
- name: Jeremy Stewart
  pic: 2
  position: Data Engineer
  social:
    - title: github
      url: http://github.com/jlstewart12
    - title: linkedin
      url: https://www.linkedin.com/in/jeremy-stewart-11512015b/
    - title: Tableau
      url: https://public.tableau.com/app/profile/jeremy3907

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/jlstewart12
  - title: linkedin
    url: https://www.linkedin.com/in/jeremy-stewart-11512015b/
  - title: Tableau
    url: https://public.tableau.com/app/profile/jeremy3907

# Postal address (add as many lines as necessary)
address: 
  - line: Indianapolis, IN

# Build settings
markdown: kramdown
permalink: pretty

# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
formspree_form_path: "f/xqkokkja"